### ISSUE TITLE
check identifier for uniqueness

### ISSUE THREAD

**Issue by FroggieFrog** [AnnoDesigner/anno-designer#133]
Add a check against all presets to make sure the identifier is unique.

**Comment by StingMcRay** [comment]
PR #356 will remove this

**Comment by FroggieFrog** [comment]
No it will not, because there is no check/validation in the PresetParser.

**Comment by StingMcRay** [comment]
My bad... i need to look into that yet

**Comment by FroggieFrog** [comment]
I can add a validator for you.
In my mind it would be run at the very end of the preset creation and check for duplicate identifiers.

**Comment by StingMcRay** [comment]
i have some name checking already 
![afbeelding](https://user-images.githubusercontent.com/18048706/133247811-a2735d82-f865-4d9a-bdba-b6d5f5d903a9.png)

and on they end it will be added 
![afbeelding](https://user-images.githubusercontent.com/18048706/133247875-9b07b573-44ee-4354-ac04-16ecc41bb829.png)

I can (or you can) do the same on Identifiers (but this is going for each anno, separated, as each anno can have the same name or even en identifier so...)

**Comment by StingMcRay** [comment]
It seams to be missing in anno 1800...
