### ISSUE TITLE
Show correct influence range of selected building

### ISSUE THREAD

**Issue by Atria1234** [AnnoDesigner/anno-designer#164]
I'm refering to building influence range, not radius. I essencially never have completely straight roads so influence range doesn't match the buildings that will be affected in the end.

I will try to implement this myself and open a PR for it. I just have a couple of question about how you think it should be implemented.

1. Change the displayed overlay displaying the influence range to follow roads. The influence range would not be a nice rotated "square". ![1](https://user-images.githubusercontent.com/7888949/81388752-073efd80-9119-11ea-9569-cac8b61484ff.png)
2. Same as 1 but don't remove the old influence range to show maximum range it can have.
3. Leave old overlay and just highlight buildings in influence range.

I also have question about if for options 1 and 3 the "Paved roads" should be building property (to increase its range) or if this should be road property instead. This then would be considered when calculating the actual influence range. I'd prefer it to be road property and letting the highlight algorithm handling it itself.

And lastly I would like to ask if there is somewhere in your codebase the sparse array representation of your grid (two dimentional dictionary with key "(X, Y) coordinates" and value "building in this spot")?

**Comment by StingMcRay** [comment]
If you select a building, and you want the range with pave roads you can select this selection box : 
![afbeelding](https://user-images.githubusercontent.com/18048706/81390911-897cf100-911c-11ea-81fe-88e30f2fb4b4.png)
![afbeelding](https://user-images.githubusercontent.com/18048706/81391068-c6e17e80-911c-11ea-9511-cf6819e8c13d.png)
Example the pub, is paved roads 41 and without paved roads it it so only 28
If the Paved roads is red (see first picture) then the box is red and when it is not selected it is green or has no color

**Comment by Atria1234** [comment]
I'm talking about this: 
![example](https://user-images.githubusercontent.com/7888949/81396145-23489c00-9125-11ea-9f46-fa155a7d3a5f.png)

This is Oil power plant with dirt roads (range 33). Two most right distileries are affected because they are up to 33 far from power plant but the most left one is not affected (even if it is displayed inside rotated "square" of influence range. The program doesn't highlight building inside the influence range right now, this is taken from my forked version. This shows how the 3. option from my first message would look like.

**Comment by StingMcRay** [comment]
I understand what you like to have, and if you have change this (what is very nice ofc) you can always ask for a Pull request.... 
You can also speak to @AgmasGold or @FroggieFrog on our discord. As i normally only do the Presets and the issue is mention that is does not show the correct influence range i answered this post

But question : If you lay whole streets, like a 1x20 does your solution still count it the right way ?

**Comment by Atria1234** [comment]
Yes, roads are searched depth first. I'll contact them in Discord, thank you.

**Comment by AgmasGold** [comment]
Hi @Atria1234,

Yeah, adding this feature is something we've thought about previously. At the moment though all we have in the app is a list of objects with x/y coordinates, which makes doing any kind of smart influence range difficult. 

Ideally, we'd probably add an array that mirrors the grid, but even this isn't quite as simple as it first appears, as the grid can be panned, resized, and buildings can be partially on screen. We'd need a data structure that could handle all the above cases whilst remaining performant.

> 1. Change the displayed overlay displaying the influence range to follow roads. The influence range would not be a nice rotated "square". 
> 2. Same as 1 but don't remove the old influence range to show maximum range it can have.
> 3. Leave old overlay and just highlight buildings in influence range.

For this, we could possibly have some kind of toggle or option to turn the max range on or off, as its still probably a useful feature to have - just not switched on all the time. 

I think I'm leaning towards a hybrid of 2/3 - but realistically, once we have the buildings that are in range of the warehouse highlighted, there may be other features that we can implement. For example, we could highlight the shortest path between the warehouse and the building.
