### ISSUE TITLE
add versioning to layouts

### ISSUE THREAD

**Issue by FroggieFrog** [AnnoDesigner/anno-designer#195]
In a discord discussion emerged a need for versioning the layouts.
It would be good to add some new properties:

- `LayoutVersion`
So users could share their layouts and remove confusion if they update them.
Also it would be good to expose it in the UI. Both as readonly when the layout is loaded and editable when it is saved.
- `Modified`
The last time the layout was modified/saved.

Best place to add would probably be `AnnoDesigner.Core/Layout/Models/SavedLayout.cs`.

**Comment by StingMcRay** [comment]
Do not forgot that the new properties need to load as well, if null, then set to 1.0.0.0 (or whatever value we gone use for this)

**Comment by FroggieFrog** [comment]
You are right, but this is an implementation detail 😄
