### ISSUE TITLE
add undo functionality to AnnoDesigner

### ISSUE THREAD

**Issue by AgmasGold** [AnnoDesigner/anno-designer#20]
It'd be useful to have some undo (Ctrl + Z) functionality, even if it just looked 1 step back.

**Comment by FroggieFrog** [comment]
What "features"/"functions"/"modifications" (however to call it) would be supported?

- change color
- change position
- added/deleted (object(s)

**Comment by AgmasGold** [comment]
From discussions on discord, we have come up with the following high-level proposal for the API:

A central "Implementation" that manages the undo/redo of AnnoObjects. 
- This "Implementation" will be provided or injected into the Canvas.
- It handles all the management of state, handling all the undo/redo.
- Events are provided that can be subscribed to by the Canvas. (Undo/Redo etc.)

The Canvas provides the following:
- All actions - e.g "X has changed in colour", "Y has changed position" - basically each time the user does something, this is provide to the Implementation.
  - The Implementation handles figuring out the changes between each action.

The following can be requested:
- A user has requested an undo - a new state is provided by the Implementation with the undo applied, or nothing is returned if we are currently in a state that has 0 recorded changes.
- A user has requested a redo - a new state is provided by the Implementation with the redo applied, or nothing is returned if we are currently in a state that has nothing to redo.
- A user has requested *n* undos - a new state is provided by the Implementation with at most *n* undos applied, or nothing is returned if we are currently in a state that has 0 recorded changes.
- A user has requested *n* redos - a new state is provided by the Implementation with at most *n* redos applied, or nothing is returned if we are currently in a state that has nothing to redo.


@FroggieFrog, this sound about right?
