### ISSUE TITLE
Disappearing icons

### ISSUE THREAD

**Issue by Rockefeller157** [AnnoDesigner/anno-designer#200]
Hello everyone, back again

This time it's a bug that makes all icons to completely disappear, on every files. Colors and sizes of buildings are still present, but not icons.
Restarting didn't solve the problem, and it doesn't come from .ad files, as it's the same everywhere.
Deleting and putting a fresh install didn't work as well.

Maybe it comes from a local file in some appdata folder?

a little screenshot to show that : 
https://cdn.discordapp.com/attachments/326223813253529611/718126542680490065/unknown.png

thanks for your time

**Comment by AgmasGold** [comment]
The "Show Icons" button isn't ticked on that screenshot - that'll be why the icons are not showing 😄 .

**Comment by StingMcRay** [comment]
Is it possible to switch the "Show Icons" to a menu bar ? 
(question asked in a DM while i was speaking to him)

**Comment by AgmasGold** [comment]
Yeah, easy enough - would that be preferred? The only reason its there at the moment is because thats where it always has been, from the time we forked the original project.

**Comment by StingMcRay** [comment]
I know :D
We can also ad a message to be sure to switch the icons off

**Comment by AgmasGold** [comment]
Either way - as this is a separate suggestion - it should probably be logged in a separate issue - that way we can track it a little more easily.

**Comment by Rockefeller157** [comment]
Well, it apparently is a missclick, meaning that if it's elsewhere (menu for instance) it wouldn't probably have happened.
It's also apparently a common probelm, so it could improve Qol of many users.

NB : I know you're still working on that settings menu, so I just suggest that lol

**Comment by AgmasGold** [comment]
QoL is always nice :)

**Comment by StingMcRay** [comment]
idea : why not make a "Show...." menu and set all those things in it 
![afbeelding](https://user-images.githubusercontent.com/18048706/83779679-8da11d80-a68c-11ea-9da8-83d913243ac9.png)

And yes it may be on an other #
