### ISSUE TITLE
Organise the "Show" toggles at the top of the canvas to a "View" menu.

### ISSUE THREAD

**Issue by AgmasGold** [AnnoDesigner/anno-designer#201]
Logging an issue for a discussion we had in #200, where it was suggested that moving all the different "Show x" toggles from the top of the canvas to a separate menu item may help prevent people accidentally clicking on it and not realising.

These toggles would nicely organise under a "View" menu, e.g:

View ->
- [x] Show Grid
- [ ] Show Labels
- [ ] Show Icons
- [x] Show True Influence Range
- [x] Show Influences

**Comment by FroggieFrog** [comment]
Should all toggles been moved to the `View` menu or should several toggles also stay on top of the canvas (e.g. `ShowInfluences`) for faster access?
So a toggle can be available in both places (menu and on top) and is automatically synchronized.

![view_menu](https://user-images.githubusercontent.com/6222752/121025730-c3984680-c7a5-11eb-80bf-7b5fbfc3eb9f.png)
