### ISSUE TITLE
Add light gray grid lines

### ISSUE THREAD

**Issue by KarolDaniluk** [AnnoDesigner/anno-designer#211]
Hello, could you please add an option to display grid lines in light-gray color?
I find these thick black lines harsh for eyes.
Here is an simple visualisation of light gray: https://imgur.com/ZqD8m8n

**Comment by FroggieFrog** [comment]
I think this is a good addition and could be done in a short time.

Ideally it will be added to the new preferences window feom PR #191

**Comment by FroggieFrog** [comment]
Currently the same color is used for both grid lines and borders of buildings.
So there will be support setting both colors separate. Either use **light gray grid lines** or **light gray borders** or **both**.

##### Some images

###### current default (grid black | border black)
![grid_black_border_black](https://user-images.githubusercontent.com/6222752/87518324-69b7fb00-c680-11ea-922e-e38cebc20c41.png)

###### grid light gray | border black
![grid_light_border_black](https://user-images.githubusercontent.com/6222752/87518245-5147e080-c680-11ea-9933-83120d22e0a9.png)

###### grid light gray | border light gray
![grid_light_border_light](https://user-images.githubusercontent.com/6222752/87518365-7b999e00-c680-11ea-9627-8b0b6371bb78.png)
