### ISSUE TITLE
Remove a file from the Recent Files list if it can no longer be found

### ISSUE THREAD

**Issue by AgmasGold** [AnnoDesigner/anno-designer#254]
Currently if a removed layout is accessed through the Recent file list, a message is shown to the user that the file could not be found, but the path itself in then just moved to the top of the list, as if it was the most recently opened file.

It would be nice if this list was pruned automatically if a file could not be found.

**Comment by FroggieFrog** [comment]
**Note:**
This issue only occurs when the file was moved the application is open.
A pruning of the list already occurs at the app start.
