### ISSUE TITLE
Building presets fix

### ISSUE THREAD

**Issue by KarolDaniluk** [AnnoDesigner/anno-designer#270]
Hello, I found few things wrong with building presets:

1. Gas mine (arctic) should have Influence Type of Range 8
2. Arctic Lodge should have Influence Type of Range 15
3. The Sky Trading Post building is missing (size 12x16)
4. Coal Storage building that is present in the Designer does not exist in the game.

**Comment by StingMcRay** [comment]
As i looked in to it, you are right.
I will fix his issue as soon as i can and i will remove the Coal Storage from the presets.
When the presets will be updated also depending on how far we are on the Anno Designer update, or it will be a separate Update

**Comment by KarolDaniluk** [comment]
Just a little clarification:
1. Gas mine should have influence type **Distance 8**
2. Artic Lodge should have influence type **Radius 15**

**Comment by StingMcRay** [comment]
I will check the data for the right numbers :D don't worry

**Comment by StingMcRay** [comment]
This issue is fixed when Update #271 will released
