### ISSUE TITLE
Wrong Menu Appeared : CultureModule

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#273]
Something went wrong on the build of presets.json version 3.5
I just noticed an extra Menu, that should not be there

This menu "CultureModule" should not be there, and will removed on the next update as this will not be a problem on the Preset Tree, however there are repeatable same objects.

If someone use this objects, i will warn that when the next presets update will applied, saves can be altered or have wrong objects, that will be marked as Unknown then.

**Comment by FroggieFrog** [comment]
So maybe recall version 3.5, fiy the issues and release 3.5.1 before too many users update to 3.5?

**Comment by StingMcRay** [comment]
My intention was to update the Presets into the new AD Version
But I can do a quick fix as you say. but hope it is not a problem i do that tomorrow then

**Comment by StingMcRay** [comment]
Btw keep in mind the Icons must be there as well then, when we do that quick fix

**Comment by StingMcRay** [comment]
Closing issue as this will be updated in Anno Designer 8.8
Presets 3.5.1
