### ISSUE TITLE
8.8 display bug after saving file

### ISSUE THREAD

**Issue by KarolDaniluk** [AnnoDesigner/anno-designer#285]
Hello, I have discovered a bug with displaying objects on canvas in the newest 8.8 release.
After saving the file the rendering size of canvavas becomes smaller thus some buildings don't display at all.
It is visible if I pan from left to right (move object closer to the right edge): https://imgur.com/a/2pz8AiX
It happens only after saving the .ad file.
Reloading the same file (without restaring an app) solves the problem.

**Comment by StingMcRay** [comment]
@AgmasGold : i think that has to do that on save the position resets to upper left corner, where the upper left object as indicator, wish top and left grid row empty

**Comment by AgmasGold** [comment]
Yeah - I think I've figured it out - the QuadTree has incorrect bounds after re-indexing when `Normalize` is called after a save. Should be a simple fix.

**Comment by KarolDaniluk** [comment]
Actually its not only display problem. When i click at some point it actually clicks a point few grid cells away to the right-bottom. The display is shifted then.

**Comment by AgmasGold** [comment]
Yeah - thats because the objects think they exist in a different position to what is visually displayed on the screen.

**Comment by AgmasGold** [comment]
You can download a version with fix from here: https://github.com/AnnoDesigner/anno-designer/releases/tag/AnnoDesignerv8.8hotfix1
