### ISSUE TITLE
Fualy range Base of Operations (1404)

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#299]
> The influence radius is not quite right in Anno 1404.
The influence area of Base of Operations (3x3, 18 Range) is 4 tiles larger in the program than in the game
And in the program you can place 6 houses along the Base of Operations in one direction but in game you can only place 5, the sixth one will be out of range. Thats the real problem

![afbeelding](https://user-images.githubusercontent.com/18048706/94941498-3e9db480-04d5-11eb-8b9c-16a08194f9f5.png)

Reported by Lywzc on Discord

**Comment by StingMcRay** [comment]
![afbeelding](https://user-images.githubusercontent.com/18048706/94985020-c544a700-0552-11eb-8389-4aa34e63719f.png)

You are right about the number of houses that fit in the range, however, the range is determined by integers, and by the fact that the building is 3, you get a final number of 16.5 (R=18 - (building/2) = 18-(3/5) = 18 - 1,5). I'll see if I can get the Radius numbers for anno 1404 as integers, so that the difference of the 0.5 no longer occurs and it will be shown well in the anno designer from now on.

**Comment by Lywzc** [comment]
Well the game's behavior on the range seems to be not that simple.
![X](https://user-images.githubusercontent.com/17480592/94986308-49694f80-0590-11eb-8b16-a0a45fad3bfc.png)
See this image, although both taverns are shown with 4 tiles in range and 4 tiles out, the left one is in range while the right one is not.

**Comment by Lywzc** [comment]
And this is my explanation:
![B](https://user-images.githubusercontent.com/17480592/94986528-1f189180-0592-11eb-9e03-0c27c290b2fb.png)
See this image, the actual area in the influence circle of the left tavern is bigger than 50%, while right one is smaller than 50%, this can explain the behavior
![C](https://user-images.githubusercontent.com/17480592/94986666-17a5b800-0593-11eb-8cf4-b8c712a1eadc.png)
For the Base of Operations, in this image, the blue line is the shown border in game while the green line is the actual border. since the house (red square on the right) has less than half area in the actual border so it is out of range.

**Comment by StingMcRay** [comment]
> See this image, the actual area in the influence circle of the left tavern is bigger than 50%, while right one is smaller than 50%, this can explain the behavior

Yes that is how it works in game and in the program, however as i said the +0,5 can be the problem in some cases, as we can't build on a half of a grid. That said, that means i need to remove all +0,5 on the Radius Ranges in whole presets, to get a better measurement of prebuild layouts

As long the radius building has a measurement of 2, 4, 6, etc then we get the right numbers, if the building is 3, 5, 7, etc then we get that +0,5, and so then need to be fixed

**Comment by StingMcRay** [comment]
As this will be an fix on the Drawings of the Radius, it will be fixed in the next release of the Anno Designer
Drawing need to be round down to nn,0 numbers

**Comment by Lywzc** [comment]
Thanks for the clarification.

**Comment by StingMcRay** [comment]
If the PR will be merged, then his will be the result : 

Left : Old situation - Right : New situation (as in game)
![afbeelding](https://user-images.githubusercontent.com/18048706/95992626-6fafaa80-0e2e-11eb-8053-a497ded3ee7d.png)
