### ISSUE TITLE
Crash when creating a new layout

### ISSUE THREAD

**Issue by jonTucich** [AnnoDesigner/anno-designer#316]
I've gotten this error with both layouts that I have created.
My work-around is to launch the app again - it works fine.

Steps to reproduce:
1. Create layout
2. Save
3. Export
4. New Layout

Result:
* Error dialog (file attached)

Setup:
* Windows 10
* App installed to C:\ProgramData\Anno.Designer
* AnnoDesigner Version: 8.81

[Logfile_AnnoDesigner.txt](https://github.com/AnnoDesigner/anno-designer/files/6016606/Logfile_AnnoDesigner.txt)

**Comment by FroggieFrog** [comment]
You can try to update your presets (3.5 - > 3.8)

**Comment by jonTucich** [comment]
How?  Is there a readme or file to that process?
I'm familiar with git / dos / etc  If it is a matter of cloning the project and copying the presets files over, I can do that..

**Comment by FroggieFrog** [comment]
There should be all you need to know: https://github.com/AnnoDesigner/anno-designer/releases/tag/Presetsv3.8

**Comment by FroggieFrog** [comment]
@jonTucich Has your issue been solved?

**Comment by jonTucich** [comment]
Unfortunately, no.  I updated the preset files and still have the issue.

**Comment by StingMcRay** [comment]
Can you send the new Logfile?

**Comment by jonTucich** [comment]
This time, I exited the app with ALT-F4 - I didn't use "File | New Canvas".
[Logfile_AnnoDesigner.txt](https://github.com/AnnoDesigner/anno-designer/files/6178207/Logfile_AnnoDesigner.txt)

As an aside, when I start the app, it asks if I want to download and install the new version.  But I already am on the new version.  Clicking either Yes or No just closes the dialog.  That might be related.  
I have tried running the app as Admin, thinking it is a permission issue, but no change.

**Comment by StingMcRay** [comment]
You said you updated the Presests.json : Loaded building presets version: 3.5.1
I also see you load files through a Dropbox directory 
delete the directory C:\Users\<Your name>\AppData\Local\AnnoDesigner
reinstall the 8.1 version do the following on the update msg : 

Keep checking the version if you have the auto updater on, it can be the download is not work as it should be. Do this through the menu 'Tools > Preferences > Update Settings' push "Check for Updates" and then "Download presets ...."

Also copy the layouts o a local drive an not on a dropbox directory

**Comment by jonTucich** [comment]
Hi,
I still had the error.
I have followed your instructions:
- deteled C:\Users<Your name>\AppData\Local\AnnoDesigner
- deleted c:\ProgramData\Anno.Designer
- created c:\Applications\Anno.Designer
- download & unzip Anno.Designer.v8.81.zip to c:\Applications\Anno.Designer
- download & unzip (with overwrite Presets.and.Icons.Update.v3.8.zip to c:\Applications\Anno.Designer
- moved saved files to C:\Users\jon\Documents\My Games\Anno1800

Launched App by clicking C:\Applications\Anno.Designer\AnnoDesigner.exe:
- Was presented dialog that a newer version exists, do I want to download and install.
- - Selected 'No'
- Was prompted to disable auto-update check
- - Selected 'Yes'
- Changed 'Game Set' to only Anno 1800
- - Selected Road 1x5
- - Placed two 1x5 roads
- - Saved  'RoadTest'
- - Exported 'RoadTest'
- Select 'File | New Canvas'
- - App displayed previous error and exited.

Restarted the application:
- Was prompted to update
- - Selected no
- Selected 'Tool | Preferences | Update Settings'
- - Noticed that 'Enable automatic check' is still enabled
- - Noticed that Presets Version was 3.8
- Selected 'Check for Updates'
- - Dialog indicating new Preset Version available
- - Selected Yes
- - Application downloaded, installed, restarted
- - Checked Preset Version: 3.9

Performed above steps for "RoadTest" - error log attached.
[Logfile_AnnoDesigner.txt](https://github.com/AnnoDesigner/anno-designer/files/6178346/Logfile_AnnoDesigner.txt)

Thanks for your help on this.  Note that it doesn't prevent me from using your application.  I just have to restart after each layout, which isn't that bad.

**Comment by StingMcRay** [comment]
What conserns me is this : System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
As user, do you have all rights in that directory ? (admin right on PC)
Can you try to save the layout on a directory like : C:\Layouts\Anno1800\
You create that your self

**Comment by FroggieFrog** [comment]
It seems to be an issue with loading some data in the background and trying to apply it on an UI thread.
I will have a closer look at this.

**Comment by jonTucich** [comment]
@StingMcRay I had just created the C:\Users\jon\Documents\My Games\Anno1800 folder for this test.  I tried as you asked:
- Created c:\AnnoLayouts
- Start Anno Designer as Administrator (This is a personal laptop, I am the admin.)
- Selected only Anno 1800 tileset
- Added two 1x5 roads
- Save as RoadTest-AnnoLayouts
- Export as RoadTest-AnnoLayouts
- File | New Canvas
: application errors and exits.
logfile attached.  

:)
[Logfile_AnnoDesigner.txt](https://github.com/AnnoDesigner/anno-designer/files/6178393/Logfile_AnnoDesigner.txt)

**Comment by FroggieFrog** [comment]
It seems that it could already be fixed and part of the next version. This version could be available in the next couple of days.

**Comment by FroggieFrog** [comment]
@jonTucich Could you please give the newest version a try.
It is currently a pre-release: [Anno Designer 9.0](https://github.com/AnnoDesigner/anno-designer/releases/tag/AnnoDesignerv9.0)

**Comment by jonTucich** [comment]
Version 9 did not have an error.

To be safe, I had installed it to a different directory (.v9.0) and I renamed the configuration folder (.v8).  
So this was a clean installation.

thanks for following up!
