### ISSUE TITLE
True Influence Range on move 

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#321]
When i have on "show true influence range" and "show Influences" the following happen when i move the whole selection in the orange box up
![afbeelding](https://user-images.githubusercontent.com/18048706/113137295-aafb3580-9224-11eb-9c96-c1eba914a09a.png)

Somehow this is the 0 line when you load a AD file i guess.. (red line)
Because when i save the file, the 0 line moves up, and so the whole selected box is normal again :
![afbeelding](https://user-images.githubusercontent.com/18048706/113137659-1b09bb80-9225-11eb-9945-42759d9eeaf2.png)

Does the process that handles this going not in negative X/Y Values (@Atria1234) ?
because the same happen if you move to the left area after load, red arrow is the 0,0 point)
![afbeelding](https://user-images.githubusercontent.com/18048706/113137946-7a67cb80-9225-11eb-97dd-80e4b715858a.png)

To test i attach the same file i use in a ZIP
[Arctic Test.zip](https://github.com/AnnoDesigner/anno-designer/files/6236250/Arctic.Test.zip)
 
 AD version 9.0
 Presets : 3.9
 Regards

**Comment by Atria1234** [comment]
Yes, the influence range algorithm considers only buildings in positive region of the canvas (it uses building positions as indexes in an array). Remainder from times before QuadTree, where you couldn't move the canvas.

Should be relatively easy to fix, I have some time now, so I'll try to fix it right away. In the meantime workaround is to...not have builds there (by saving/normalizing the canvas).

**Comment by StingMcRay** [comment]
I tested this because of #288 / #289 (see #290) to see of that all worked now, so i stumbled into this one now.
So, yeah i know we changed a lot on moving canvas :D

Workaround:
To all users : If you have this, just save the file; then all will be viewing normal.
