### ISSUE TITLE
Add a "blocking building"

### ISSUE THREAD

**Issue by FroggieFrog** [AnnoDesigner/anno-designer#374]
Because it was requested on discord a couple of times, it would be benficial to add a `blocking building` to the presets.
This could be used for outlines of island or just marking a blocked area.

Properties of the `blocker building`:
- has a size of 1x1
- is **not** respected in the statstistics
- is **not** respected when calculating the layout size
- is **not** respected when calculating the influence
- does **not** have a label
- should **not** have a border

Open questions:
- Which predefined color does it have?
- What is the name of the `Template`? (e.g. `Blocker`)
- Should it be visible/respected in the `Selected buildings` area?
- Is it beneficial to add more sizes? (similiar to the different road presets)
- Implement it as `ExtraPreset` inside of `PresetParser`? (similiar to the different road presets)

**Comment by StingMcRay** [comment]
As we do add extra preset information in 9.2, like for the coastal building,  
`                       "BlockedAreaLength": 0.0,`
`			"BlockedAreaWidth": 0.0,`
`			"Direction": "Down",`
we should can add this one too before we release 9.2, the extra information block should be called `IsBlocker` and from there we can exclude them from all things (if value is `1`). The Template name should be called `"Blocker Area"`.
Default it should be Borderless too 

My answer on the open Q's:
> Which predefined color does it have? 

That will be black, that is what the most will use


> Should it be visible/respected in the Selected buildings area?

No, as it is exclude from all other things as well (or optional in case the Island Creators want to count there stuff)


> Is it beneficial to add more sizes? (similiar to the different road presets)

1x1 will be the common usable one.


> Implement it as ExtraPreset inside of PresetParser? (similiar to the different road presets)

It will be placed in the ExtraPreset section and i will try to place it below the "- road presets" with the name "Block tile"

**Comment by FroggieFrog** [comment]
`Block tile` or `Block Tile`or `Blocking tile` or `Blocking Tile` seems to be a good "name" for it (I like your suggestion)

I kind of resist to add a new property `IsBlocker` to ALL buildings in the presets. I think it is more flexible/expendable to implement the logic via a special `Template`.
Also I forgot about the property `Identifier`. It could be set to something like `Blocker`.
The `Template` could be called "BlockerArea" and the `Identifier` could be part of this `Template`.
So in the future more identifiers could be added to this template (like with multiple `Police Stations`).
At the moment there are properties `Road` and `PavedStreet` on EVERY building. I think it would also be simpler to manage this via `Template` and different values for `Identifier` (like `Dirt Road` and `Paved Street`).
I know this would be a breaking change.

**What is your opinion on the decision between `special Property on every building` and `special Template with (possibly) multiple identifiers`?**

**Comment by StingMcRay** [comment]
So the checker to exclude it from things (or calculate in the future) will be on the template name.... 
In that case we must be sure that template is Unique for all existing and future anno's
 
but i understand your view about the road ones.... but that is something already used in pre 8.0 and we took it as was, because the 2 first `Road tile` and `Borderless road tile` where and still are part of the code and not of the presets so we left that as is/was
