### ISSUE TITLE
Set working directory to where executable is

### ISSUE THREAD

**Issue by Atria1234** [AnnoDesigner/anno-designer#387]
So logs directory isn't created where the layouts are, when creating the layout by file association.

**Comment by FroggieFrog** [comment]
Are there steps to reproduce the issue?
I never had that issue  and can't reproduce it.

**Comment by StingMcRay** [comment]
If you load an AD file from an other directory, you will get if you save it on the same location, and close Anno Designer then you see a LOG directory in that loaded AD file folder....

**Comment by StingMcRay** [comment]
Example what i have seen 
![afbeelding](https://user-images.githubusercontent.com/18048706/145186764-b3c79f08-70c3-4993-9265-ffbcdd89f7a7.png)

**Comment by FroggieFrog** [comment]
Alright. I'm still unable to reproduce, but have an idea why it is occuring.
There will be a PR to fix this and also updates some dependencies.
