### ISSUE TITLE
[Question] [Enhancement] when copy pasting: paste at least tiles which have free space

### ISSUE THREAD

**Issue by Acidello** [AnnoDesigner/anno-designer#393]
Right now if we copy-paste a block of stuff (buildings, roads, etc...) on a surface which doesn't allow the whole thing to be pasted, nothing gets pasted.
A cool option could be: when copy-pasting, build the tiles/objects which can be placed (which don't overlap already existing things), as it happens ingame with the copy tool.

**Comment by StingMcRay** [comment]
I understand your question, however we made it that way, so if something when wrong with unintended copy & past, the copied section could not be past just like that, and needed a free area.

**Comment by StingMcRay** [comment]
However, it's up to the others how they thing about this too

**Comment by Acidello** [comment]
I see, yeah that is a good point. Perhaps it could be made as a "toggle" option?

**Comment by StingMcRay** [comment]
That is an option to look into.
@FroggieFrog / @Atria1234 / @AgmasGold

**Comment by Atria1234** [comment]
I guess holding shift could alter the default behaviour? Placing non overlapping building of selected layout even if some buildings do overlap?

**Comment by StingMcRay** [comment]
If that not overrule other things, then sure
