### ISSUE TITLE
Viewport is moved to top left corner after save

### ISSUE THREAD

**Issue by Atria1234** [AnnoDesigner/anno-designer#394]
It is done because the layout needs to be normalized before it is saved.
Either:
- move viewport back to original position after the save is done
- make a copy of the layout, then normalize and save the copy

Since some players might have used the fact that viewport was reset as a hint that save is done, add star to window title as long as there are unsaved changes.

**Comment by StingMcRay** [comment]
This issue is here because of the conversation on Discord, read down from the following link 
https://discord.com/channels/571011757317947406/571064812042321927/921726181399740426
