### ISSUE TITLE
Making roads counting towards efficiency %

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#401]
Question came on Annoverse, and therefore this request by me

Making an option in Settings to count roads to efficiency calculation, as `StatisticsCalculationHelper` supports this already, it would easy to implant this option

**Comment by Atria1234** [comment]
Should there be also a setting for including ignored objects, since StatisticsCalculationHelper also supports counting them?

**Comment by StingMcRay** [comment]
Blocking items should not be counted (never)
What other objects are ignored beside that one ?

**Comment by Atria1234** [comment]
Whatever object which has template "Blocker" but I think only blocker tile has that so far. Let's hope that Acidello uses same template for stuff like mines and coastline.

**Comment by StingMcRay** [comment]
he was changing all stuff i though with the 9.2 (let hope then :D)
That Scenario Layout he made with that anyway as fare i know
