### ISSUE TITLE
Anno 2070 - Wrongly Building Radius

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#403]
The radius of buildings in Anno 2070 can be wrong, and must be checked on all buildings
As we had never a problem reported, and because we could not set decimals into this number, we could not fix it before.
As we can add decimals now (since the sky scrapers in anno 1800, version 9.1) we can fix this now.

The problem is lying in the same as the problem in Anno 1404, grid wise it is very clear to see
In game:
![afbeelding](https://user-images.githubusercontent.com/18048706/147883367-82482a96-bd89-4fe2-86c2-c0d2ac7c0017.png)
in AD :
![afbeelding](https://user-images.githubusercontent.com/18048706/147883377-013e68c8-ebde-4769-ac6a-820a91e6bb29.png)
*green is default radius (7,0) , orange is how it should be (6,5)*

I will look into this in the next week

**Comment by Atria1234** [comment]
I believe this might be caused by that special edge case we had in the code for modifying influence radius for some specific buildings.

**Comment by StingMcRay** [comment]
No, i thought we had build that only for anno 1404 but had not the time to check yet.

**Comment by Joe78man** [comment]
I don't know if you guys see the same I see but the "Should be" is wrong IMO. Check the amount of scuares, the radius is ok. You have the same radious all arround and the field in the top, the one redded has 6 slots within the range and 6 outside, when the bottom one has 9 and only 3 out of the radious. 
The same logic is applied in AD which matches the actual influence. The orange version matches the game and the green one doesnt

**Comment by StingMcRay** [comment]
@Joe78man : The green one is the ONE that is used in the AD at the moment, and we need to make it to the orange one, so i need to change the preset logic's that round up those ones. 
I was forgotten to mention maybe that the conversations took place on Discord, so here is the link :
[Issue conversation on discord](https://discord.com/channels/571011757317947406/571011757317947410/927231926677409874)

**Comment by StingMcRay** [comment]
Sorry for the delay, but 
Here is the problem, and this is thru the whole Assets.xml or Anno 2070
The used ROUND Numbers in this file, and so, i must adjust all buildings with a radius, to get the right numbers.

As we know that this problem probably only occurs on this farm as far we know, the simple solution is to change the radius in the field, as de-scripted above from 7,0 to 6,5

If i want to solve this issue i must rewrite the whole Anno 2070 data get from the assets. and to simple solution to minus all with like 0,5 will harm other buildings then.

So, with other words, if ALL Radius buildings has this issue, i will be happy to do that, but not for just 1 building, sorry

*This topic will be closed and not solved as there is a work around for now, but if more complains about more buildings will come i will reopen this topic*
