### ISSUE TITLE
File Association Registry

### ISSUE THREAD

**Issue by DerBaronTV** [AnnoDesigner/anno-designer#420]
Due to the command line changes with Version 9.3 the registry association needs an update

From: "PATH\AnnoDesigner.exe" "%1"
To: "PATH\AnnoDesigner.exe" open "%1"

**Comment by StingMcRay** [comment]
I will check in on that but maybe i should do both then 
or does the registry also uses the second one to open the complete AD

**Comment by StingMcRay** [comment]
But just a Q why do you need it ?

**Comment by DerBaronTV** [comment]
Yeah, I double click my layouts in the explorer instead of opening in the program

**Comment by StingMcRay** [comment]
i tried the key in regedit with the 'open' in it, then it does not work

**Comment by StingMcRay** [comment]
![afbeelding](https://user-images.githubusercontent.com/18048706/175656337-afaf0c95-9d01-4cbc-9a8d-b16f663e86fa.png)
works normal as it

**Comment by FroggieFrog** [comment]
@StingMcRay You are referencing version 9.2, but the issue is with 9.3.

The fix should be easy, but I have no time this weekend.
@DerBaronTV It seems you already found a workaround.

**Comment by StingMcRay** [comment]
Ow darn i forgot to update :shame me:

**Comment by DerBaronTV** [comment]
> @StingMcRay You are referencing version 9.2, but the issue is with 9.3.
> 
> The fix should be easy, but I have no time this weekend. @DerBaronTV It seems you already found a workaround.

yeah, I work a lot with the registry so it was easy to fix
