### ISSUE TITLE
Copy Objects with the mouse goes wrong

### ISSUE THREAD

**Issue by StingMcRay** [AnnoDesigner/anno-designer#429]
Copy/Paste and clearing the mouse pointer on Anno Designer 9.2 has some issues when doing this with the mouse, Copy/Paste clearing mouse pointer (esc) with the key strokes are doing it oke, no problems there..

how to reproduce : 
1 : selected 2/3 objects
2 : click on the middle mouse button (to copy and rotate 90 degrees)
3 : place the copied objects somewhere else,, click left mouse button to place them.
4 : move mouse to an other location and click the right mouse button (to release the mouse pointer)

result : you will see that where the original objects where are now on the mouse pointer from step 4
if you try to select those objects it will not been selected. 
This should not be the behavior of the copy with mouse buttons, the original objects should stay where they where from step 1,
and the clear mouse pointer should not place or move those selected and copied original objects.

**Comment by FroggieFrog** [comment]
I can confirm the issue and add some images to clarify.
Version `9.1` does **not** have the issue, but version `9.2` has it and the current main branch also has it.

#### Version `9.1`
<details>
  <summary>Click to expand!</summary>

![rotate_91](https://user-images.githubusercontent.com/6222752/176396734-5a741290-1146-426c-ad04-9c2f0d19216e.gif)
</details>

#### Version `9.2`+
<details>
  <summary>Click to expand!</summary>

![rotate_92](https://user-images.githubusercontent.com/6222752/176396861-154ce1c0-9ec3-4272-9c66-d7175dfbf210.gif)
</details>

**Comment by StingMcRay** [comment]
Then we need to loop back what is changed from **`9.1`** to **`9.2`** what cost this issue...

**Comment by FroggieFrog** [comment]
It is not that easy.
But from what I understand it is caused by some changes of the `QuadTree` (which I still not fully understand).
So my best guess is that @Atria1234 needs to have a look at this.

The method `AnnoCanvas.TryPlaceCurrentObjects()` could be a good starting point.

**Comment by Atria1234** [comment]
@FroggieFrog could you provide list of commands used to reproduce this? I see:

1. Select objects
2. ??? (which cause selection to copy to mouse cursor while also rotating?)
3. Place down objects in cursor

And after being done
- selected objects in step 1. are still copied to mouse cursor
- both original and new copy of selected objects are on canvas and selectable

**Comment by FroggieFrog** [comment]
1. select objects by mouse (**yellow** circle around cursor means **left** button is pressed)
2. press middle mouse button (**blue** circle around cursor means **middle** button is pressed)
3. place objects with left mouse button
4. try to clear objects from cursor with right mouse button (**red** circle around cursor means **right** button is pressed)

**Comment by Atria1234** [comment]
Appears to be clone of #396

Caused by https://github.com/AnnoDesigner/anno-designer/commit/621d458b2a5939b226319543b227650ff475672d#diff-9356fda68a12ab98d19dae0d5982f1b8f8aa126b2808d456f3bb3f90fa5aef14R2696 . Easy fix.
