### ISSUE TITLE
How is efficiency calculated?

### ISSUE THREAD

**Issue by MichaelHochriegl** [AnnoDesigner/anno-designer#450]
I have built this pig layout but I don't quite understand how the efficiency rating is only at 14%:
![image](https://github.com/AnnoDesigner/anno-designer/assets/78933445/f8c74e3d-683b-4a1c-b2cc-65414a24a8c7)

Can someone explain to me why the rating is so low?

**Comment by StingMcRay** [comment]
It can be that there is an object somewhere you have placed somewhere else..
If you are on our discord, tag my name and put your ad file in discord so we can check that, if you self can't find it

Regards
Sting McRay

**Comment by FroggieFrog** [comment]
@MichaelHochriegl If you could upload/add the layout file, it would be easier to check. But the picture is clearly not all of your layout.

**Comment by MichaelHochriegl** [comment]
Thanks for the hint with the random placed object somewhere. I zoomed all the way out and for some unknown reason I found a Silo way out in the open. After deleting it the efficiency is calculated correctly.
