### ISSUE TITLE
add option to rotate complete layout

### ISSUE THREAD

**Issue by FroggieFrog** [AnnoDesigner/anno-designer#56]
isuue migrated from [https://github.com/JcBernack/anno-designer/issues/22](https://github.com/JcBernack/anno-designer/issues/22) point 1

- Add (context) menu to canvas "rotate complete layout by 90°"?
- Add shortcut?

**Comment by StingMcRay** [comment]
As Agmas build in the rotation, for multiple objects, its up to him what i find abt that, because i knwo it was a pain work to get the multiple selected objects to rotate

**Comment by AgmasGold** [comment]
This shouldn't be difficult to add - my rotation code works on any `List<AnnoObject>` - instead of rotating the current selection, we can just rotate the `PlacedObjects` list.
