### ISSUE TITLE
Fix wrong structure sizes

### ISSUE THREAD

**Issue by Braste** [AnnoDesigner/anno-designer#60]
Please check the structure sizes, some of them are wrong. For example here are the correct sizes, that i found till now:

Big Betty: 7x4
Depot: 10x4
Small Trading Post: 7x11
Pier: 7x8
Sailing Shipyard: 7x15

**Comment by FroggieFrog** [comment]
I just checked without playing the game.
presets.json 3.1.1
[Wiki](https://anno1800.fandom.com/wiki/Buildings)

Big Betty
presets: 4x4
wiki: 4x6

Depot
presets: 14x4
wiki: 4x10

Small Trading Post
presets: 4x7
wiki: ---

Pier
presets: 4x6
wiki: 6x7

Sailing Shipyard
presets: 4x6
wiki: 6x15

**Comment by StingMcRay** [comment]
I know but coastal buildings only measured the "Placeable " Building ground not the sea area that is 'Blocked'. On the Wiki is stated that also
The sizes in Preset are  directly from the data files of anno

**Comment by FroggieFrog** [comment]
Then it makes sense to use existing values in presets.json.
Another approach would be to extend the datamodel and add separate blockers for land and sea. I don't know if those values exist in the extracted data.

I think the missing feature is to plan a harbour. But this could be complicated.

**Comment by StingMcRay** [comment]
I do not know of there is a part of "Blocked' area data, i can look, but i can not do that today, i run some tests of an other branch and then i gone do something else today.
So, i case of this, i will look tomorrow on the buildblocker data files to see of i can find some of this data

**Comment by StingMcRay** [comment]
As additional information : 
The size that is in the preset is the size the building NEED on the coastline as example : the green box of the shipyard (sail) is counted as size)
![afbeelding](https://user-images.githubusercontent.com/18048706/57389531-ac4b9100-71ba-11e9-85c5-ecaed58b99d0.png)
Ofc : the measurements of the total size of the shipyard (and his sea blocking area) is also imported to know on pre-build harbors in the Anno Designer : So you know why this is.

I still will look into this matter tomorrow *if i have some time* :)

**Comment by StingMcRay** [comment]
Extra Information : 
I have found some values i can do something with, however i need to check all coastal buildings to see of all values are right 
I can tel you already the 'x15' is a measurement to mark the building as 'endless water blocker' *means nothing can be build before this building on the water line*

**Comment by AgmasGold** [comment]
Can this issue be closed?

**Comment by StingMcRay** [comment]
Yeah, i think it can be closed, as i can not find any data to do this or make this idea working
